application.host: http://localhost:8080
application.cors-origins: '*'
application.temp-folder=logs/myTemp
application.management-url: http://localhost:8888
application.questionnaire-url: http://localhost:9999

feature.oidc.enabled=true
feature.oidc.authServerHost=http://localhost:7080
feature.oidc.application-host=${application.host}
feature.oidc.authServerUrl=${feature.oidc.authServerHost}
feature.oidc.realm=sabiane
feature.oidc.principalAttribute=preferred_username
feature.oidc.clientId=myclient

springdoc.swagger-ui.path: /
springdoc.swagger-ui.oauth.clientId: ${feature.oidc.clientId}
springdoc.swagger-ui.oauth2RedirectUrl: ${application.host}/swagger-ui/oauth2-redirect.html
springdoc.swagger-ui.try-it-out-enabled: true
springdoc.swagger-ui.doc-expansion: none

feature.swagger.enabled: true
spring.security.oauth2.resourceserver.jwt.issuer-uri: ${feature.oidc.authServerUrl}/realms/${feature.oidc.realm}

############# Logging #############
logging.config=classpath:log4j2.xml