spring:
  config:
    name: sabdatab
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${feature.oidc.authServerUrl}/realms/${feature.oidc.realm}

application:
  host: http://localhost:8080
  cors-origins: '*'
  temp-folder: logs/myTemp
  management-url: http://localhost:8888
  questionnaire-url: http://localhost:9999

feature:
  oidc:
    enabled: true
    authServerHost: http://localhost:7080
    application-host: ${application.host}
    authServerUrl: ${feature.oidc.authServerHost}
    realm: sabiane
    principalAttribute: preferred_username
    clientId: myclient
  swagger:
    enabled: true

springdoc:
  swagger-ui:
    path: /
    oauth:
      clientId: ${feature.oidc.clientId}
    oauth2RedirectUrl: ${application.host}/swagger-ui/oauth2-redirect.html
    try-it-out-enabled: true
    doc-expansion: none

logging:
  appender: CONSOLE # CONSOLE | ROLLING_FILE
  level:
    root: INFO
    fr:
      insee:
        sabianedata: INFO
  pattern:
    console: "%d{YYYY-MM-dd HH:mm:ss.SSS} [%X{id}][%X{user}][%X{method} %X{path}] [%thread] %-5level %logger{36} - %m%n"
    file: ${logging.pattern.console}
  logback:
    rollingpolicy:
      max-history: 90